name: Deploy Static website on a S3 Bucket

on:
  workflow_dispatch:
    inputs:
      bucketname:
        description: "Enter a s3 bucket name"
        required: true
  push:
    branches: [ "master" ]
    
jobs:
  create_deploy_s3_bucket:
    runs-on: ubuntu-latest

    steps:
       - uses: actions/checkout@v4

       - name: "Configure AWS Credentials" 
         uses: aws-actions/configure-aws-credentials@v4
         with:     
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: ap-southeast-1
           
       - name: Create a s3 bucket
         run: |
           aws s3 mb s3://${{ github.event.inputs.bucketname }}

       - name: Deploying and Synchronizing to S3 Bucket
         uses: jakejarvis/s3-sync-action@v0.5.1
         with:
           args: --exclude '.git/*'
         env:
           AWS_S3_BUCKET: ${{ github.event.inputs.bucketname }}
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           AWS_REGION: 'ap-southeast-1'
              
